version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: vectrieve-qdrant
    ports:
      - "6333:6333"  # Відкриваємо порт назовні, щоб локальний Python його бачив
    volumes:
      - ./qdrant_data:/qdrant/storage
    restart: always